### ISSUE TITLE
meow_search does not work with MSVC

### ISSUE THREAD

**Issue by mmozeiko** [cmuratori/meow_hash#22]
Because `malloc(a)` is defined as `_aligned_malloc(4,a)` in `meow_test.h`.

Thus any malloc will allocate only 4 bytes with alignment a. This means that either _aligned_malloc will crash program if a is not power of two, or memory corruption will happen when a > 4.

Not sure of the intention here, but should malloc be overridden at all? It is used only to allocate entry/file structures or path strings, not the file contents itself.

Also I think `aligned_alloc` in `meow_test.h` should be in `#ifdef _WIN32` and not inside `#ifdef _MSC_VER`, because clang & gcc on Windows does not have aligned_alloc. They have _aligned_malloc though because they use MSVC runtime.

**Comment by cmuratori** [comment]
Sorry, that must have been a screw-up from dealing with the Linux build.  I will take care of it.

\- Casey

**Comment by cmuratori** [comment]
I patched it to use the correct memory order.  Other than that, I'm not sure there's that much you can do here.  You can't leave it as a malloc, because of course you cannot free() things allocated by _aligned_malloc of MSVC (you have to call _aligned_free).  It's fantastic.

As for the _WIN32, my understanding was that CLANG _does_ define _MSC_VER when compiling on Windows... is that not true?

\- Casey

**Comment by mmozeiko** [comment]
It is only true if clang is build with MSVC. If it is build by gcc then it won't define _MSC_VER. It basically "pretends" to be compiler it is build with to be compatible with header files / C runtime provided by original compiler. But gcc on Windows is special, because it does not have its own C runtime, it partially is compatible with MSVC functions / runtime, that is why _aligned_malloc exists even if clang is built by gcc and does not define _MSC_VER. Fun stuff.

**Comment by cmuratori** [comment]
That does sound fun!  :/  Well, since I can't test any of that, if you want to go through and pick out what you think are the correct defines for things and put it in a pull request, I'm happy to just your judgement, Martins.  Based on what you said, there are probably a couple places where we're if'ing on the wrong thing currently, then...

\- Casey

**Comment by cmuratori** [comment]
Thanks Martins!  I have merged in the request.

\- Casey

**Comment by despair86** [comment]
@mmozeiko even more interesting: mingw32 and mingw-w64 still have an inline implementation of `_aligned_*` functions in their runtime library, since a default build can target Microsoft C Runtime 6.1 or 7.0, which correspond to the "private" system libc in the NT 5.x releases.
